### ISSUE TITLE
Add pre-commit for Markdown formatting

### ISSUE THREAD

**Issue by vwxyzjn** [vwxyzjn/cleanrl#183]
## Problem Description

We could add the `prettier` pre-commit utilty to help format all the markdown files.

```
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier
        files: \.(js|ts|jsx|tsx|css|less|html|json|markdown|md|yaml|yml)$
```
